# Sample config for Prometheus.

global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'Mikrotik'

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 10s
    scrape_timeout: 10s
    tls_config:
      insecure_skip_verify: true
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    #static_configs:
      #- targets: ['localhost:9090']

  - job_name: Mikrotik
    static_configs:
      - targets:
        - 192.168.22.1 # mikrotik_ip
    metrics_path: /snmp
    params:
      module: [mikrotik]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: mk_snmp_exporter:9116  # The SNMP exporter's real hostname:port.
  - job_name: 'ping_lan_devices_blackbox'
    metrics_path: /probe
    params:
      module: [icmp]  # Use the icmp module for ping monitoring
    static_configs:
      - targets:
          - 192.168.22.11
          - 192.168.22.34
          - 192.168.22.20
          - 192.168.22.53
          - 192.168.22.16
          - 192.168.22.5                                      
          - 192.168.22.40                                      
          - 192.168.22.23                                      
          - 192.168.22.51
          - 192.168.22.45
          - 192.168.22.41                                      
          - 192.168.22.42                                      
          - 192.168.22.43                                      
          - 192.168.22.44
          - 192.168.22.31
          - 192.168.22.52                                      
          - 192.168.22.8                                      
          - 192.168.22.9                                      
          - 192.168.22.32
          - 192.168.22.50
          - 192.168.22.7                                      
          - 192.168.22.6                                      
          - 192.168.22.39                                      
          - 192.168.22.38
          - 192.168.22.40
          - 192.168.22.49
          - 192.168.22.1
          - 192.168.22.3
          - 10.10.20.1
          - 192.168.22.45
          - 192.168.22.46


    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
